/* Release 3.22. */

ALTER TABLE book ADD type VARCHAR(16) NOT NULL DEFAULT 'Book';
ALTER TABLE cd ADD type VARCHAR(16) NOT NULL DEFAULT 'CD';
ALTER TABLE dvd ADD type VARCHAR(16) NOT NULL DEFAULT 'DVD';
ALTER TABLE videogame ADD type VARCHAR(16) NOT NULL DEFAULT 'Video Game';
